[package]
name = "kanade"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
kanade-shared = { path = "../kanade-shared" }

anyhow     = { workspace = true }
async-nats = { workspace = true }
bytes      = { workspace = true }
chrono     = { workspace = true }
clap       = { workspace = true }
futures    = { workspace = true }
reqwest    = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio      = { workspace = true }
tracing    = { workspace = true }
tracing-subscriber = { workspace = true }
uuid       = { workspace = true }
